{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.datasets import load_boston\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.ensemble import RandomForestRegressor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "outputs": [
    {
     "data": {
      "text/plain": "(506, 13)"
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dataset = load_boston()\n",
    "\n",
    "dataset.data.shape"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "outputs": [],
   "source": [
    "x_full,y_full = dataset.data,dataset.target\n",
    "n_samples = x_full.shape[0]\n",
    "n_features = x_full.shape[1]\n"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "outputs": [],
   "source": [
    "rng = np.random.RandomState(0)\n",
    "missing_rate= 0.5\n",
    "n_missing_samples =  int(np.floor(n_samples * n_features * missing_rate))"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "outputs": [],
   "source": [
    "missing_features =  rng.randint(0,n_features,n_missing_samples)\n",
    "missing_samples = rng.randint(0,n_samples,n_missing_samples)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "          0     1      2    3      4      5     6       7    8      9     10  \\\n",
      "0        NaN  18.0    NaN  NaN  0.538    NaN  65.2  4.0900  1.0  296.0   NaN   \n",
      "1    0.02731   0.0    NaN  0.0  0.469    NaN  78.9  4.9671  2.0    NaN   NaN   \n",
      "2    0.02729   NaN   7.07  0.0    NaN  7.185  61.1     NaN  2.0  242.0   NaN   \n",
      "3        NaN   NaN    NaN  0.0  0.458    NaN  45.8     NaN  NaN  222.0  18.7   \n",
      "4        NaN   0.0   2.18  0.0    NaN  7.147   NaN     NaN  NaN    NaN  18.7   \n",
      "..       ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   ...   \n",
      "501      NaN   NaN    NaN  0.0  0.573    NaN  69.1     NaN  1.0    NaN  21.0   \n",
      "502  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0   NaN   \n",
      "503      NaN   NaN  11.93  NaN  0.573  6.976  91.0     NaN  NaN    NaN  21.0   \n",
      "504  0.10959   0.0  11.93  NaN  0.573    NaN  89.3     NaN  1.0    NaN  21.0   \n",
      "505  0.04741   0.0  11.93  0.0  0.573  6.030   NaN     NaN  1.0    NaN   NaN   \n",
      "\n",
      "         11    12  \n",
      "0       NaN  4.98  \n",
      "1    396.90  9.14  \n",
      "2       NaN   NaN  \n",
      "3       NaN   NaN  \n",
      "4       NaN  5.33  \n",
      "..      ...   ...  \n",
      "501     NaN  9.67  \n",
      "502  396.90  9.08  \n",
      "503     NaN  5.64  \n",
      "504  393.45  6.48  \n",
      "505  396.90  7.88  \n",
      "\n",
      "[506 rows x 13 columns]\n"
     ]
    }
   ],
   "source": [
    "x_missing = x_full.copy()\n",
    "y_missing = y_full.copy()\n",
    "x_missing[missing_samples,missing_features] = np.nan\n",
    "x_missing = pd.DataFrame(x_missing)\n",
    "print(x_missing)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "outputs": [],
   "source": [
    "from sklearn.impute import SimpleImputer\n",
    "imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')\n",
    "x_missing_mean = imp_mean.fit_transform(x_missing)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "outputs": [],
   "source": [
    "imp_0 = SimpleImputer(missing_values=np.nan, strategy=\"constant\",fill_value=0)\n",
    "x_missing_0 = imp_0.fit_transform(x_missing)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "outputs": [],
   "source": [
    "x_missing_reg = x_missing.copy()\n",
    "sortindex = np.argsort(x_missing_reg.isnull().sum(axis=0)).values"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 304, in fit\n",
      "    X, y = self._validate_data(X, y, multi_output=True,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 433, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 814, in check_X_y\n",
      "    X = check_array(X, accept_sparse=accept_sparse,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float32').\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import cross_val_score\n",
    "\n",
    "for i in sortindex:\n",
    "    df = x_missing_reg\n",
    "    fillc = df.iloc[:,i]\n",
    "    df = pd.concat([df.iloc[:,df.columns != i],pd.DataFrame(y_full)],axis=1)\n",
    "    df_0 =SimpleImputer(missing_values=np.nan,\n",
    "                        strategy='constant',fill_value=0).fit_transform(df)\n",
    "    Ytrain = fillc[fillc.notnull()]\n",
    "    Ytest = fillc[fillc.isnull()]\n",
    "    Xtrain = df_0[Ytrain.index,:]\n",
    "    Xtest = df_0[Ytest.index,:]\n",
    "    rfc = RandomForestRegressor(n_estimators=100)\n",
    "    rfc = rfc.fit(Xtrain, Ytrain)\n",
    "    Ypredict = rfc.predict(Xtest)\n",
    "    x_missing_reg.loc[x_missing_reg.iloc[:,i].isnull(),i] = Ypredict\n",
    "    X = [x_full,x_missing_mean,x_missing_0,x_missing_reg]\n",
    "    mse = []\n",
    "    std = []\n",
    "    for x in X:\n",
    "        estimator = RandomForestRegressor(random_state=0, n_estimators=100)\n",
    "        scores = cross_val_score(estimator,x,y_full,scoring='neg_mean_squared_error',\n",
    "                                 cv=5).mean()\n",
    "        mse.append(scores * -1)\n",
    "\n",
    "\n",
    "\n"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "outputs": [
    {
     "data": {
      "text/plain": "<Figure size 864x432 with 1 Axes>",
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAx0AAAGDCAYAAABOan2JAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAkmklEQVR4nO3dedglVXkv7N+jjYEAARNajyOtqNFIFBWJU5QkxsRZ0cQBjUSPYvRETWKM0cQonk85ajzBz6M2TijiGDUfTkf9joKzMtiAA8bI4IQ4IApETITn/LHrlc1rz/R6d9N939f1Xm/tqlVVT61d3df+7bWqu7o7AAAAo1xj0QUAAAA7NqEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6ADYyVTVoVX1oUXXsSlV1VV1s63c9wNV9ZhtXdNoVfWqqvr7jWx/blW9aSVrAtgWhA6ArVBV51TVPRdw3sOq6hNb0H7N9OF91dK67j6uu++1jes6tKounn5+UlWXz72+eFuea3N09727+w0rfd6rqruf2N3PT5KqOriqvnlVjje995dM78P3q+otVbX3VTzmL9xT21JVHVNV/1FVF00/X6iqF1bVXltwjIX8+QQ2TOgA4Cqbgswe3b1Hknsn+fbS62kdi3Pb6T24aZJrJ3nuYsvZLC/q7j2TrE7yp0nulOSTVbX7YssCtpbQAXAVTaMPn6yq/1lVF1bVWVV1l2n9N6rqu/NTfaZvcl9VVR+evsk9sar2nbb9wrfIVXVCVf3XqrpVklclufP0zfWF0/b7VtXnq+rH0/meO1fex6bfF0773Hn5aMlU60lV9aPp912Wnfv50/VdVFUfqqp9trB/rl9V76yq71XV2VX1lLlt16yqZ1XV16bjn1JVN5rb/Z5V9dWq+mFV/a+qqrk+/0RVvWTadnZV3Xt5n82d4yXTN/1nVdWT5/t4+bfiy6cwVdWdqupT03t7WlUdPLftsOmYF001HLqe6991Gv3ZZ3r9d1X1s6r6len1f6+qf5qWj5le757kA0muPzdidP3pkNeqqjdO5/xiVR24Oe9Dd/84yfFJfmPZe3N8VV1QVf9WVY+f23ZQVZ083VfnV9VLp03ru6euMV3XudP9/saaRibm7unHVNXXp/fh2ZtZ86XdfVKSByT5tcwCSKpqv6r6SFX9YDrecTWN4FTVsUlunOQ9U33PmNa/o6q+M93nH6uqW29ODcC2IXQAbBu/leT0zD4YvTnJW5PcMcnNkjwqycurav4b/0OTPD/JPknWJTluUyfo7i8neWKST08jCHtPmy5J8idJ9k5y3yR/VlUPmrbdffq997TPp+ePWVW/muR9SV421f7SJO+rql+ba/bIzD7sXSfJtZI8fVO1zh3/Gknek+S0JDdI8ntJnlZVfzA1+cskj0hynyS/kuSxSf597hD3y6wfb5vkj5P8wdy230rylcz68EVJXrsUSpZ5/HSc2yU5MMlDt6D+G2TWP/89ya9mdu3vrKrVUzB4WZJ7T9/K3yWz9/JKuvvSJCcluce06u5Jzk1y17nXJy7b55L84ojRt6fND8js/to7sxDx8s28lmsneVCSz8ytfkuSbya5fmb98oKq+r1p21FJjuruX0myX5K3z9WbXPmeOmz6+Z3MRlT2WE9dd0vy65ndA8+pWYjeLN19UZIPJ/ntpctJ8sKp7lsluVGmEZzufnSSrye5/1Tfi6Z9PpDk5pndx6dmM/7MAduO0AGwbZzd3a/v7suSvC2zD0FHdPdPu/tDSf4jswCy5H3d/bHu/mmSZ2c2enGjXzzspnX3Cd19Rndf3t2nZ/ZB8h6b2m9y3yRf7e5ju/tn3f2WJGcmuf9cm9d39792908y++B5wBaUd8ckq7v7iO7+j+4+K8mrkzx82v5fk/xdd3+lZ07r7h/M7X9kd1/Y3V9P8tFl5z63u1899fkbklwvyXXXU8MfJ/mn7v5Gd1+Q2YfVzfWoJO/v7vdP/fvhJCdnFpKS5PIk+1fVbt19Xnd/cQPHOTHJPabRldtkFlbuUVW7Tn308S2o6RNTPZclOTazQLYxp9ZsVOz7mY0ArE2S6X67W5K/mUYU1iV5TZJHT/v9Z5KbVdU+3X1xd3/mF458hUOTvLS7z+rui5P8bZKH15Wf+3hed/+ku0/LLIRuqu7lvp1Z8Et3/1t3f3j68/W9zMLyRu/57n5dd180/Zl7bpLb1hY8JwJcNUIHwLZx/tzyT5Kku5evmx/p+MbSwvQh7YLMvrXdYlX1W1X10Wn60o8yGw3Z3ClQ18/sW/d552Y2KrHkO3PL/54rX8em7JvZFKELl36SPCtXhIMbJfnaRvbf2Ll/vq27l0ZH1lfb9TPX3/nF692YfZP80bL675bketNoxMMy6+/zqup9VXXLDRznxCQHJ7l9kjMy+9b+Hpk9q/Bv3f39LahpeZ/sWht/qPv206jYrklemeTjU9i5fpILplGEJfPv/eOS3CLJmTWbdne/jZxj+X10bpJVuXIIvCr3Uaa6LkiSqrpOVb21qr5VVT9O8qZs5J6fptgdWbNpfD9Ocs60aYumCgJbT+gAWIyfj2pM065+NbNvci+ZVv/yXNv/Mrfc6znWmzObZnOj7t4rs+c+aiPt5307sw/W826c5Fub2G9zfSOzUaC953727O77zG3fbxuda0POy1x/Z3Z98y7Jhvv7G0mOXVb/7t19ZJJ09we7+/czG2U5M7NRnPX5VGZTix6c5MTu/tJUx32zbGrVnE29d1uku/8zs5GMmyTZP9PIQVXtOdfs5+99d3+1ux+R2XSk/5Hkn6cpZeura/l9dOMkP8uVw/hWm/6M3DNXjAi9cKrjNtP0r0flins+66nxkUkeOB1jryRrlg69LeoDNk3oAFiM+1TV3arqWpk92/HZafrP9zL70Peo6dvZx+bKH8rPT3LDab8le2b2jfWlVXVQZh+wlnwvsylAN91AHe9PcouqemRVraqqh2X2oPF7t8lVJp9L8uOq+puq2m26pv2r6o7T9tckeX5V3bxmbrPseZJt4e1JnlJVN5yea3jmsu3rMpsKtMv0UPb8Mx9vSnL/qvqDqfZda/ZP2d6wqq5bVQ+YPoj/NMnFSS5bXwHTSMwpSZ6cK0LGp5Icng2HjvOT/Nq2mgJUVdfM7NmcnyQ5q7u/MdXwwum6bpPZ6MZxU/tHVdXq7r48yYXTYS7L+u+ptyT5i6q6yRQQXpDkbd39s6tY8y9V1R2S/EuSHyZ5/bRpz8z6+8LpuZu/Xrbr+cvq2zOz9+gHmQXMF1yVuoAtJ3QALMabk/xDZtNF7pDZnPglj8/sQ9QPktw6sw+GSz6S5ItJvlNVS1NynpTkiKq6KMlzcsUDv0sfdv+fzP650Qur6k7zRUzPT9wvyV9N53tGkvtt4XSfDZqeO7h/Zs9inJ3ZcwWvyezb5mQ2F//tST6U5MdJXptkt21x7jmvTvLBzJ4jODXJu5Zt//vMgt0Pkzwvs/dmqf5vZPYN+bMy+7D9jczem2tMP3+V2bf8F2Q2XepJG6njxCS7ZBbEll7vmSv+Nagr6e4zM/swf9b03m3V9Lskp9Xs/0r5YZLHJHnw9GxLMnuIf810De9O8g/TcytJ8odJvjjte1SSh0/PfqzvnnpdZs+XfCyz9/nSJH++lfUmyTOm+/mCJG/MLLDdZZrSlszep9sn+VFmD/ovf09fmOTvpvqePh3j3MwC/Zdy5YfpgRVQ3dt09BaATaiqY5J8s7v/btG17Iyqak1mH4x3uarfxAOweYx0AAAAQwkdAADAUKZXAQAAQxnpAAAAhhI6AACAoTb2P5iyg9hnn316zZo1iy4DAIAd3CmnnPL97l69fL3QsRNYs2ZNTj755EWXAQDADq6qzl3fetOrAACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhlq16AJYAZecm3zu8EVXsX4HrV10BQAADGakAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoTYZOqrqsqpaV1VfqKr3VNXeK1DXMFV1WFW9fPA5Dqiq+2xpu6p6QFU9c2RtAACw0jZnpOMn3X1Ad++f5IIkT76qJ62qa17VY2zBuVat1LnmHJBkk6FjebvuPr67jxxUEwAALMSWTq/6dJIbJElV7VdV/7uqTqmqj1fVLefWf6aqTqqqI6rq4mn9wVX10ap6c5IzquqaVfXiqd3pVXX41O56VfWxudGV357aHjO9PqOq/mJqe8B0rtOr6t1Vde1p/QlV9YKqOjHJUzd0MdMxXznVdVZV3aOqXldVX66qY+baXVxV/1hVp1bV/6mq1XPnOXBa3qeqzqmqayU5IsnDpmt4WFUdVFWfqqrPT79/fQPtfj4KU1X7Tuc6ffp947maXzYd56yqeugWvocAALCiNjt0TKMTv5fk+GnV0Un+vLvvkOTpSV4xrT8qyVHdfcck3152mIOSPLu7fyPJ45L8aGp3xySPr6qbJHlkkg929wFJbptkXWYjAjfo7v27+zeTvH463huT/E133ybJGUn+Ye5ce3f3Pbr7HzdxaddO8rtJ/iLJe5L8zyS3TvKbVXXA1Gb3JKd29+2TnLjsPFfS3f+R5DlJ3jaNEL0tyZlJ7t7dt5u2vWAD7ea9PMkbp2s7LsnL5rZdL8ndktwviZERAAC2a5sz9Wi3qlqXZE2SU5J8uKr2SHKXJO+oqqV2vzT9vnOSB03Lb07ykrljfa67z56W75XkNnPf1O+V5OZJTkryuqraJcm/dPe6qjoryU2r6v9N8r4kH6qqvTILFidO+78hyTvmzrX8Q/yGvKe7u6rOSHJ+d5+RJFX1xema1yW5fO54b0ryrs089pK9kryhqm6epJPsshn73DnJIdPysUleNLftX7r78iRfqqrrrm/nqnpCkickyY3/yx5bWC4AAGw7m/1MR5J9k1wrs2c6rpHkwukb+qWfW23GsS6ZW67MRkqW9r9Jd3+ouz+W5O5JvpXk2Kr6k+7+YWajHidM53/NFp5rY346/b58bnnp9YZCWU+/f5Yr+nDXjZzj+Uk+Oj0Xc/9NtN2Qnluer7OWN0yS7j66uw/s7gNX7701pwMAgG1js6dXdfePkjwls6lUP0lydlX9UZLUzG2npp9J8pBp+eEbOeQHk/zZNKKRqrpFVe1eVfsm+W53vzrJa5Pcvqr2SXKN7n5nkr9Pcvupnh9W1W9Px3t0ZlOfRrhGkqURmUcm+cS0fE6SO0zL889WXJRkz7nXe2UWopLksI20m/epXNF/h86dEwAArla26EHy7v58ktMy+zB8aJLHVdVpSb6Y5IFTs6cl+cuq+lxmzx78aAOHe02SLyU5taq+kGRtZiMLBydZV1Wfzyy8HJXZw+snTNO8jknyt9MxHpPkxVV1embPfRyxJdezBS5JcuuqOiWz5z+WzvOSzILTp5LsM9f+o0l+Y+kB8cymRr2wqj6Z5JobaTfvKUn+dLq2R2cjD8QDAMD2rLp706225IBVv5zZlKyuqocneUR3P3BT+23Pquri7r7aPhhx4K1W98lvOGTTDRfhoLWLrgAAgG2kqk7p7gOXrx/xf1jcIcnLa/aE+YVJHjvgHAAAwNXENg8d3f3xzB763mFcnUc5AABg0bb0PwcEAADYIkIHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQ61adAGsgN33TQ5au+gqAADYSRnpAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoVYtugDGO/fc5PDDF10FAMDKWrt20RWwxEgHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDLSx0VFVX1bFzr1dV1feq6r2Dz3tMVT108DkeVFW/saXtquqIqrrnyNoAAGClLXKk45Ik+1fVbtPr30/yrQXWsy09KMkmQ8fydt39nO7+/wfVBAAAC7Ho6VUfSHLfafkRSd6ytKGqdq+q11XVSVX1+ap64LR+TVV9vKpOnX7uMq0/uKpOqKp/rqozq+q4qqqNnbyqzqmqF1TVp6vq5Kq6fVV9sKq+VlVPnDvux6rq3VX1pap6VVVdY9p28dyxHjqNotwlyQOSvLiq1lXVflX1+Ok6Tquqd1bVL2+g3c9HYarq96brPmPqh1+aq/l507WfUVW33CbvBAAADLLo0PHWJA+vql2T3CbJZ+e2PTvJR7r7jkl+J7MP57sn+W6S3+/u2yd5WJKXze1zuyRPy2z04KZJ7roZNXyju++c5ONJjkny0CR3SnLEXJuDkvxVkt9Msl+SQzZ0sO7+VJLjk/x1dx/Q3V9L8q7uvmN33zbJl5M8bgPtkiRTfxyT5GHd/ZtJViX5s7nTfH+6/lcmefpmXCMAACzMQkNHd5+eZE1moxzvX7b5XkmeWVXrkpyQZNckN06yS5JXV9UZSd6RK09j+lx3f7O7L0+ybjr2phw//T4jyWe7+6Lu/l6SS6tq77njntXdl2U2GnO3zb/KJLNpZB+faj40ya030f7Xk5zd3f86vX5DkrvPbX/X9PuUbOAaq+oJ0+jNyZde+r0tLBcAALadVYsuILMP/S9JcnCSX5tbX0ke0t1fmW9cVc9Ncn6S22YWmi6d2/zTueXLsnnXt7TP5cv2v3xu/162T69n/a4bOccxSR7U3adV1WGZXevGbHRaWK6oc4PX2N1HJzk6SVavPnB5/QAAsGIWPb0qSV6X5IjuPmPZ+g8m+fOl5zKq6nbT+r2SnDeNZjw6yTVXoMaDquom07McD0vyiWn9+VV1q2n9g+faX5Rkz7nXeyY5r6p2yWykY0PtlpyZZE1V3Wx6/egkJ26D6wAAgBW38NAxTYc6aj2bnp/ZVKrTq+oL0+skeUWSx1TVZ5LcIrN/BWu0Tyc5MskXkpyd5N3T+mcmeW+SjyQ5b679W5P89fQg+H5J/j6z51U+nFmg2FC7JEl3X5rkT5O8Y5qSdXmSV424MAAAGK26zbzZmKo6OMnTu/t+Cy5lq61efWAfcsjJiy4DAGBFrV276Ap2PlV1SncfuHz9wkc6AACAHdv28CD5dq27T8jsX88CAAC2gpEOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoVYtugDG23ffZO3aRVcBAMDOykgHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDrVp0AYx37o/OzeHvOXzRZQCwE1h7/7WLLgHYDhnpAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAobab0FFVD66qdct+Lq+qew8418Xb+pjrOceztqZdVX1qTEUAALAY203o6O53d/cBSz9JXpHk40k+uDn718x2cz1JNit0LG/X3XcZUAsAACzM9vQh/eeq6hZJnpPk0d19+bTur6vqpKo6vaqeN61bU1VfrqpXJDk1yY2q6sVV9YWqOqOqHraJ8xxcVSdW1dur6l+r6siqOrSqPjftv9/U7piqelVVfXxqd79p/WFV9fK54713OuaRSXabRmuOm7b9S1WdUlVfrKonTOvW1+7i6Xet71qm459QVf9cVWdW1XFVVduu9wEAYNtategClquqXZK8OcnTu/vr07p7Jbl5koOSVJLjq+ruSb6e5NeT/Gl3P6mqHpLkgCS3TbJPkpOq6mPdfd5GTnnbJLdKckGSs5K8prsPqqqnJvnzJE+b2q1Jco8k+yX5aFXdbEMH7O5nVtV/m0Zsljy2uy+oqt2mut65gXZLDlnftUzbbpfk1km+neSTSe6a5BMbuUYAAFiY7XGk4/lJvtjdb51bd6/p5/OZjWjcMrMQkiTndvdnpuW7JXlLd1/W3ecnOTHJHTdxvpO6+7zu/mmSryX50LT+jMyCxpK3d/fl3f3VzMLJLbfwup5SVacl+UySG83VvyEbu5bPdfc3p1GgdcvqTJJU1ROq6uSqOvnSH126haUCAMC2s12NdFTVwUkekuT2yzcleWF3r13Wfk2SS5a121I/nVu+fO715bly//Sy/TrJz3Ll4Lbr+k4wXdc9k9y5u/+9qk7YUNv53Taz5suynvexu49OcnSSrL756uW1AwDAitluRjqq6tpJXp/kT7r7omWbP5jksVW1x9T2BlV1nfUc5mNJHlZV16yq1UnunuRz26jEP6qqa0zPedw0yVeSnJPkgGn9jTKb/rXkP6epYkmyV5IfToHjlknutIF2K3UtAACwYrankY4nJrlOklcuey76hd39tqq6VZJPT9suTvKozL7ln/fuJHdOclpmIxHP6O7vbKP6vpLZFKfrJnlid19aVZ9McnZmU7G+kNnUryVHJzm9qk5N8tgkT6yq06fjfGZ97br70E1dyxRaAADgaqO6zbzZlKo6Jsl7u/ufF13L1lh989V9yEsPWXQZAOwE1t5/7aYbATusqjqluw9cvn67mV4FAADsmLan6VXbre4+bNE1AADA1ZWRDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKFWLboAxtt3r32z9v5rF10GAAA7KSMdAADAUEIHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMtWrRBbACzj03OfzwRVex7a1du+gKAADYDEY6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKFjE6rqsqpaN/ezZiNtD6uql0/Lz62qp2/G8S/exPa9q+pJW1w4AABsJ1YtuoCrgZ909wELPP/eSZ6U5BULrAEAALaakY6tUFXnVNU+0/KBVXXCFux7k6r6dFWdVFXPn1u/R1X9n6o6tarOqKoHTpuOTLLfNMry4o20AwCA7ZKRjk3brarWTctnd/eDr+Lxjkryyu5+Y1U9eW79pUke3N0/ngLNZ6rq+CTPTLL/0mhLVa1aX7vu7qtYFwAADCF0bNq2nl511yQPmZaPTfI/puVK8oKqunuSy5PcIMl117P/htp950qNqp6Q5AlJcuM99tiG5QMAwJYROrbOz3LF1LRdt2L/9Y1KHJpkdZI7dPd/VtU5Gzj2ZrXr7qOTHJ0kB65ebRQEAICF8UzH1jknyR2m5YdspN36fDLJw6flQ+fW75Xku1OQ+J0k+07rL0qy52a0AwCA7ZLQsXWel+Soqvp4ksu2cN+nJnlyVZ2UWYBYclySA6vq5MzCyJlJ0t0/SPLJqvpCVb14Q+0AAGB7VZ4/3vEduHp1n3zIIYsuY9tbu3bRFQAAMKeqTunuA5evN9IBAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDrVp0AayAffdN1q5ddBUAAOykjHQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDCR0AAMBQ1d2LroHBqup7Sc4dfJp9knx/8Dm4Mn2+8vT5ytPni6HfV54+X3n6fIx9u3v18pVCB9tEVZ3c3Qcuuo6diT5fefp85enzxdDvK0+frzx9vrJMrwIAAIYSOgAAgKGEDraVoxddwE5In688fb7y9Pli6PeVp89Xnj5fQZ7pAAAAhjLSAQAADCV0sEWq6kZV9dGq+nJVfbGqnjqt/9Wq+nBVfXX6fe1F17qj2EifP7eqvlVV66af+yy61h1FVe1aVZ+rqtOmPn/etN59PtBG+t29PlhVXbOqPl9V751eu9cHW0+fu88Hq6pzquqMqX9Pnta511eI6VVskaq6XpLrdfepVbVnklOSPCjJYUku6O4jq+qZSa7d3X+zuEp3HBvp8z9OcnF3v2SR9e2IqqqS7N7dF1fVLkk+keSpSQ6J+3yYjfT7H8a9PlRV/WWSA5P8Snffr6peFPf6UOvp8+fGfT5UVZ2T5MDu/v7cOvf6CjHSwRbp7vO6+9Rp+aIkX05ygyQPTPKGqdkbMvtQzDawkT5nkJ65eHq5y/TTcZ8PtZF+Z6CqumGS+yZ5zdxq9/pAG+hzFsO9vkKEDrZaVa1Jcrskn01y3e4+L5l9SE5ynQWWtsNa1udJ8t+q6vSqep0h4W1rmvqwLsl3k3y4u93nK2AD/Z6410f6pyTPSHL53Dr3+lj/lF/s88R9Plon+VBVnVJVT5jWuddXiNDBVqmqPZK8M8nTuvvHi65nZ7CePn9lkv2SHJDkvCT/uLjqdjzdfVl3H5DkhkkOqqr9F1zSTmED/e5eH6Sq7pfku919yqJr2VlspM/d5+Pdtbtvn+TeSZ5cVXdfdEE7E6GDLTbNtX5nkuO6+13T6vOnZw+WnkH47qLq2xGtr8+7+/zpA9rlSV6d5KBF1rij6u4Lk5yQ2XMF7vMVMt/v7vWh7prkAdNc97cm+d2qelPc6yOtt8/d5+N197en399N8u7M+ti9vkKEDrbI9KDna5N8ubtfOrfp+CSPmZYfk+T/W+nadlQb6vOlvyQnD07yhZWubUdVVaurau9pebck90xyZtznQ22o393r43T333b3Dbt7TZKHJ/lIdz8q7vVhNtTn7vOxqmr36R9jSVXtnuRemfWxe32FrFp0AVzt3DXJo5OcMc27TpJnJTkyydur6nFJvp7kjxZT3g5pQ33+iKo6ILM5quckOXwRxe2grpfkDVV1zcy+nHl7d7+3qj4d9/lIG+r3Y93rK87f6SvvRe7zoa6b5N2z7/GyKsmbu/t/V9VJca+vCP9kLgAAMJTpVQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHADuVquqqOnbu9aqq+l5VvXd6fd2qem9VnVZVX6qq90/r11TVT6pq3dzPnyzqOgCuTvw/HQDsbC5Jsn9V7dbdP0ny+0m+Nbf9iCQf7u6jkqSqbjO37WvdfcCKVQqwgzDSAcDO6ANJ7jstPyLJW+a2XS/JN5dedPfpK1gXwA5J6ABgZ/TWJA+vql2T3CbJZ+e2/a8kr62qj1bVs6vq+nPb9ls2veq3V7JogKsr06sA2Ol09+lVtSazUY73L9v2waq6aZI/THLvJJ+vqv2nzaZXAWwFIx0A7KyOT/KSXHlqVZKkuy/o7jd396OTnJTk7itdHMCOROgAYGf1uiRHdPcZ8yur6ner6pen5T2T7Jfk6wuoD2CHYXoVADul7v5mkqPWs+kOSV5eVT/L7Mu513T3SdN0rP2qat1c29d198uGFwtwNVfdvegaAACAHZjpVQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABD/V8HqUfy3dkHfQAAAABJRU5ErkJggg==\n"
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": "<Figure size 864x432 with 1 Axes>",
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAx0AAAGDCAYAAABOan2JAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAkmklEQVR4nO3dedglVXkv7N+jjYEAARNajyOtqNFIFBWJU5QkxsRZ0cQBjUSPYvRETWKM0cQonk85ajzBz6M2TijiGDUfTkf9joKzMtiAA8bI4IQ4IApETITn/LHrlc1rz/R6d9N939f1Xm/tqlVVT61d3df+7bWqu7o7AAAAo1xj0QUAAAA7NqEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6ADYyVTVoVX1oUXXsSlV1VV1s63c9wNV9ZhtXdNoVfWqqvr7jWx/blW9aSVrAtgWhA6ArVBV51TVPRdw3sOq6hNb0H7N9OF91dK67j6uu++1jes6tKounn5+UlWXz72+eFuea3N09727+w0rfd6rqruf2N3PT5KqOriqvnlVjje995dM78P3q+otVbX3VTzmL9xT21JVHVNV/1FVF00/X6iqF1bVXltwjIX8+QQ2TOgA4Cqbgswe3b1Hknsn+fbS62kdi3Pb6T24aZJrJ3nuYsvZLC/q7j2TrE7yp0nulOSTVbX7YssCtpbQAXAVTaMPn6yq/1lVF1bVWVV1l2n9N6rqu/NTfaZvcl9VVR+evsk9sar2nbb9wrfIVXVCVf3XqrpVklclufP0zfWF0/b7VtXnq+rH0/meO1fex6bfF0773Hn5aMlU60lV9aPp912Wnfv50/VdVFUfqqp9trB/rl9V76yq71XV2VX1lLlt16yqZ1XV16bjn1JVN5rb/Z5V9dWq+mFV/a+qqrk+/0RVvWTadnZV3Xt5n82d4yXTN/1nVdWT5/t4+bfiy6cwVdWdqupT03t7WlUdPLftsOmYF001HLqe6991Gv3ZZ3r9d1X1s6r6len1f6+qf5qWj5le757kA0muPzdidP3pkNeqqjdO5/xiVR24Oe9Dd/84yfFJfmPZe3N8VV1QVf9WVY+f23ZQVZ083VfnV9VLp03ru6euMV3XudP9/saaRibm7unHVNXXp/fh2ZtZ86XdfVKSByT5tcwCSKpqv6r6SFX9YDrecTWN4FTVsUlunOQ9U33PmNa/o6q+M93nH6uqW29ODcC2IXQAbBu/leT0zD4YvTnJW5PcMcnNkjwqycurav4b/0OTPD/JPknWJTluUyfo7i8neWKST08jCHtPmy5J8idJ9k5y3yR/VlUPmrbdffq997TPp+ePWVW/muR9SV421f7SJO+rql+ba/bIzD7sXSfJtZI8fVO1zh3/Gknek+S0JDdI8ntJnlZVfzA1+cskj0hynyS/kuSxSf597hD3y6wfb5vkj5P8wdy230rylcz68EVJXrsUSpZ5/HSc2yU5MMlDt6D+G2TWP/89ya9mdu3vrKrVUzB4WZJ7T9/K3yWz9/JKuvvSJCcluce06u5Jzk1y17nXJy7b55L84ojRt6fND8js/to7sxDx8s28lmsneVCSz8ytfkuSbya5fmb98oKq+r1p21FJjuruX0myX5K3z9WbXPmeOmz6+Z3MRlT2WE9dd0vy65ndA8+pWYjeLN19UZIPJ/ntpctJ8sKp7lsluVGmEZzufnSSrye5/1Tfi6Z9PpDk5pndx6dmM/7MAduO0AGwbZzd3a/v7suSvC2zD0FHdPdPu/tDSf4jswCy5H3d/bHu/mmSZ2c2enGjXzzspnX3Cd19Rndf3t2nZ/ZB8h6b2m9y3yRf7e5ju/tn3f2WJGcmuf9cm9d39792908y++B5wBaUd8ckq7v7iO7+j+4+K8mrkzx82v5fk/xdd3+lZ07r7h/M7X9kd1/Y3V9P8tFl5z63u1899fkbklwvyXXXU8MfJ/mn7v5Gd1+Q2YfVzfWoJO/v7vdP/fvhJCdnFpKS5PIk+1fVbt19Xnd/cQPHOTHJPabRldtkFlbuUVW7Tn308S2o6RNTPZclOTazQLYxp9ZsVOz7mY0ArE2S6X67W5K/mUYU1iV5TZJHT/v9Z5KbVdU+3X1xd3/mF458hUOTvLS7z+rui5P8bZKH15Wf+3hed/+ku0/LLIRuqu7lvp1Z8Et3/1t3f3j68/W9zMLyRu/57n5dd180/Zl7bpLb1hY8JwJcNUIHwLZx/tzyT5Kku5evmx/p+MbSwvQh7YLMvrXdYlX1W1X10Wn60o8yGw3Z3ClQ18/sW/d552Y2KrHkO3PL/54rX8em7JvZFKELl36SPCtXhIMbJfnaRvbf2Ll/vq27l0ZH1lfb9TPX3/nF692YfZP80bL675bketNoxMMy6+/zqup9VXXLDRznxCQHJ7l9kjMy+9b+Hpk9q/Bv3f39LahpeZ/sWht/qPv206jYrklemeTjU9i5fpILplGEJfPv/eOS3CLJmTWbdne/jZxj+X10bpJVuXIIvCr3Uaa6LkiSqrpOVb21qr5VVT9O8qZs5J6fptgdWbNpfD9Ocs60aYumCgJbT+gAWIyfj2pM065+NbNvci+ZVv/yXNv/Mrfc6znWmzObZnOj7t4rs+c+aiPt5307sw/W826c5Fub2G9zfSOzUaC953727O77zG3fbxuda0POy1x/Z3Z98y7Jhvv7G0mOXVb/7t19ZJJ09we7+/czG2U5M7NRnPX5VGZTix6c5MTu/tJUx32zbGrVnE29d1uku/8zs5GMmyTZP9PIQVXtOdfs5+99d3+1ux+R2XSk/5Hkn6cpZeura/l9dOMkP8uVw/hWm/6M3DNXjAi9cKrjNtP0r0flins+66nxkUkeOB1jryRrlg69LeoDNk3oAFiM+1TV3arqWpk92/HZafrP9zL70Peo6dvZx+bKH8rPT3LDab8le2b2jfWlVXVQZh+wlnwvsylAN91AHe9PcouqemRVraqqh2X2oPF7t8lVJp9L8uOq+puq2m26pv2r6o7T9tckeX5V3bxmbrPseZJt4e1JnlJVN5yea3jmsu3rMpsKtMv0UPb8Mx9vSnL/qvqDqfZda/ZP2d6wqq5bVQ+YPoj/NMnFSS5bXwHTSMwpSZ6cK0LGp5Icng2HjvOT/Nq2mgJUVdfM7NmcnyQ5q7u/MdXwwum6bpPZ6MZxU/tHVdXq7r48yYXTYS7L+u+ptyT5i6q6yRQQXpDkbd39s6tY8y9V1R2S/EuSHyZ5/bRpz8z6+8LpuZu/Xrbr+cvq2zOz9+gHmQXMF1yVuoAtJ3QALMabk/xDZtNF7pDZnPglj8/sQ9QPktw6sw+GSz6S5ItJvlNVS1NynpTkiKq6KMlzcsUDv0sfdv+fzP650Qur6k7zRUzPT9wvyV9N53tGkvtt4XSfDZqeO7h/Zs9inJ3ZcwWvyezb5mQ2F//tST6U5MdJXptkt21x7jmvTvLBzJ4jODXJu5Zt//vMgt0Pkzwvs/dmqf5vZPYN+bMy+7D9jczem2tMP3+V2bf8F2Q2XepJG6njxCS7ZBbEll7vmSv+Nagr6e4zM/swf9b03m3V9Lskp9Xs/0r5YZLHJHnw9GxLMnuIf810De9O8g/TcytJ8odJvjjte1SSh0/PfqzvnnpdZs+XfCyz9/nSJH++lfUmyTOm+/mCJG/MLLDdZZrSlszep9sn+VFmD/ovf09fmOTvpvqePh3j3MwC/Zdy5YfpgRVQ3dt09BaATaiqY5J8s7v/btG17Iyqak1mH4x3uarfxAOweYx0AAAAQwkdAADAUKZXAQAAQxnpAAAAhhI6AACAoTb2P5iyg9hnn316zZo1iy4DAIAd3CmnnPL97l69fL3QsRNYs2ZNTj755EWXAQDADq6qzl3fetOrAACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhlq16AJYAZecm3zu8EVXsX4HrV10BQAADGakAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoTYZOqrqsqpaV1VfqKr3VNXeK1DXMFV1WFW9fPA5Dqiq+2xpu6p6QFU9c2RtAACw0jZnpOMn3X1Ad++f5IIkT76qJ62qa17VY2zBuVat1LnmHJBkk6FjebvuPr67jxxUEwAALMSWTq/6dJIbJElV7VdV/7uqTqmqj1fVLefWf6aqTqqqI6rq4mn9wVX10ap6c5IzquqaVfXiqd3pVXX41O56VfWxudGV357aHjO9PqOq/mJqe8B0rtOr6t1Vde1p/QlV9YKqOjHJUzd0MdMxXznVdVZV3aOqXldVX66qY+baXVxV/1hVp1bV/6mq1XPnOXBa3qeqzqmqayU5IsnDpmt4WFUdVFWfqqrPT79/fQPtfj4KU1X7Tuc6ffp947maXzYd56yqeugWvocAALCiNjt0TKMTv5fk+GnV0Un+vLvvkOTpSV4xrT8qyVHdfcck3152mIOSPLu7fyPJ45L8aGp3xySPr6qbJHlkkg929wFJbptkXWYjAjfo7v27+zeTvH463huT/E133ybJGUn+Ye5ce3f3Pbr7HzdxaddO8rtJ/iLJe5L8zyS3TvKbVXXA1Gb3JKd29+2TnLjsPFfS3f+R5DlJ3jaNEL0tyZlJ7t7dt5u2vWAD7ea9PMkbp2s7LsnL5rZdL8ndktwviZERAAC2a5sz9Wi3qlqXZE2SU5J8uKr2SHKXJO+oqqV2vzT9vnOSB03Lb07ykrljfa67z56W75XkNnPf1O+V5OZJTkryuqraJcm/dPe6qjoryU2r6v9N8r4kH6qqvTILFidO+78hyTvmzrX8Q/yGvKe7u6rOSHJ+d5+RJFX1xema1yW5fO54b0ryrs089pK9kryhqm6epJPsshn73DnJIdPysUleNLftX7r78iRfqqrrrm/nqnpCkickyY3/yx5bWC4AAGw7m/1MR5J9k1wrs2c6rpHkwukb+qWfW23GsS6ZW67MRkqW9r9Jd3+ouz+W5O5JvpXk2Kr6k+7+YWajHidM53/NFp5rY346/b58bnnp9YZCWU+/f5Yr+nDXjZzj+Uk+Oj0Xc/9NtN2Qnluer7OWN0yS7j66uw/s7gNX7701pwMAgG1js6dXdfePkjwls6lUP0lydlX9UZLUzG2npp9J8pBp+eEbOeQHk/zZNKKRqrpFVe1eVfsm+W53vzrJa5Pcvqr2SXKN7n5nkr9Pcvupnh9W1W9Px3t0ZlOfRrhGkqURmUcm+cS0fE6SO0zL889WXJRkz7nXe2UWopLksI20m/epXNF/h86dEwAArla26EHy7v58ktMy+zB8aJLHVdVpSb6Y5IFTs6cl+cuq+lxmzx78aAOHe02SLyU5taq+kGRtZiMLBydZV1Wfzyy8HJXZw+snTNO8jknyt9MxHpPkxVV1embPfRyxJdezBS5JcuuqOiWz5z+WzvOSzILTp5LsM9f+o0l+Y+kB8cymRr2wqj6Z5JobaTfvKUn+dLq2R2cjD8QDAMD2rLp706225IBVv5zZlKyuqocneUR3P3BT+23Pquri7r7aPhhx4K1W98lvOGTTDRfhoLWLrgAAgG2kqk7p7gOXrx/xf1jcIcnLa/aE+YVJHjvgHAAAwNXENg8d3f3xzB763mFcnUc5AABg0bb0PwcEAADYIkIHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQ61adAGsgN33TQ5au+gqAADYSRnpAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoVYtugDGO/fc5PDDF10FAMDKWrt20RWwxEgHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDLSx0VFVX1bFzr1dV1feq6r2Dz3tMVT108DkeVFW/saXtquqIqrrnyNoAAGClLXKk45Ik+1fVbtPr30/yrQXWsy09KMkmQ8fydt39nO7+/wfVBAAAC7Ho6VUfSHLfafkRSd6ytKGqdq+q11XVSVX1+ap64LR+TVV9vKpOnX7uMq0/uKpOqKp/rqozq+q4qqqNnbyqzqmqF1TVp6vq5Kq6fVV9sKq+VlVPnDvux6rq3VX1pap6VVVdY9p28dyxHjqNotwlyQOSvLiq1lXVflX1+Ok6Tquqd1bVL2+g3c9HYarq96brPmPqh1+aq/l507WfUVW33CbvBAAADLLo0PHWJA+vql2T3CbJZ+e2PTvJR7r7jkl+J7MP57sn+W6S3+/u2yd5WJKXze1zuyRPy2z04KZJ7roZNXyju++c5ONJjkny0CR3SnLEXJuDkvxVkt9Msl+SQzZ0sO7+VJLjk/x1dx/Q3V9L8q7uvmN33zbJl5M8bgPtkiRTfxyT5GHd/ZtJViX5s7nTfH+6/lcmefpmXCMAACzMQkNHd5+eZE1moxzvX7b5XkmeWVXrkpyQZNckN06yS5JXV9UZSd6RK09j+lx3f7O7L0+ybjr2phw//T4jyWe7+6Lu/l6SS6tq77njntXdl2U2GnO3zb/KJLNpZB+faj40ya030f7Xk5zd3f86vX5DkrvPbX/X9PuUbOAaq+oJ0+jNyZde+r0tLBcAALadVYsuILMP/S9JcnCSX5tbX0ke0t1fmW9cVc9Ncn6S22YWmi6d2/zTueXLsnnXt7TP5cv2v3xu/162T69n/a4bOccxSR7U3adV1WGZXevGbHRaWK6oc4PX2N1HJzk6SVavPnB5/QAAsGIWPb0qSV6X5IjuPmPZ+g8m+fOl5zKq6nbT+r2SnDeNZjw6yTVXoMaDquom07McD0vyiWn9+VV1q2n9g+faX5Rkz7nXeyY5r6p2yWykY0PtlpyZZE1V3Wx6/egkJ26D6wAAgBW38NAxTYc6aj2bnp/ZVKrTq+oL0+skeUWSx1TVZ5LcIrN/BWu0Tyc5MskXkpyd5N3T+mcmeW+SjyQ5b679W5P89fQg+H5J/j6z51U+nFmg2FC7JEl3X5rkT5O8Y5qSdXmSV424MAAAGK26zbzZmKo6OMnTu/t+Cy5lq61efWAfcsjJiy4DAGBFrV276Ap2PlV1SncfuHz9wkc6AACAHdv28CD5dq27T8jsX88CAAC2gpEOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoVYtugDG23ffZO3aRVcBAMDOykgHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDrVp0AYx37o/OzeHvOXzRZQCwE1h7/7WLLgHYDhnpAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAobab0FFVD66qdct+Lq+qew8418Xb+pjrOceztqZdVX1qTEUAALAY203o6O53d/cBSz9JXpHk40k+uDn718x2cz1JNit0LG/X3XcZUAsAACzM9vQh/eeq6hZJnpPk0d19+bTur6vqpKo6vaqeN61bU1VfrqpXJDk1yY2q6sVV9YWqOqOqHraJ8xxcVSdW1dur6l+r6siqOrSqPjftv9/U7piqelVVfXxqd79p/WFV9fK54713OuaRSXabRmuOm7b9S1WdUlVfrKonTOvW1+7i6Xet71qm459QVf9cVWdW1XFVVduu9wEAYNtategClquqXZK8OcnTu/vr07p7Jbl5koOSVJLjq+ruSb6e5NeT/Gl3P6mqHpLkgCS3TbJPkpOq6mPdfd5GTnnbJLdKckGSs5K8prsPqqqnJvnzJE+b2q1Jco8k+yX5aFXdbEMH7O5nVtV/m0Zsljy2uy+oqt2mut65gXZLDlnftUzbbpfk1km+neSTSe6a5BMbuUYAAFiY7XGk4/lJvtjdb51bd6/p5/OZjWjcMrMQkiTndvdnpuW7JXlLd1/W3ecnOTHJHTdxvpO6+7zu/mmSryX50LT+jMyCxpK3d/fl3f3VzMLJLbfwup5SVacl+UySG83VvyEbu5bPdfc3p1GgdcvqTJJU1ROq6uSqOvnSH126haUCAMC2s12NdFTVwUkekuT2yzcleWF3r13Wfk2SS5a121I/nVu+fO715bly//Sy/TrJz3Ll4Lbr+k4wXdc9k9y5u/+9qk7YUNv53Taz5suynvexu49OcnSSrL756uW1AwDAitluRjqq6tpJXp/kT7r7omWbP5jksVW1x9T2BlV1nfUc5mNJHlZV16yq1UnunuRz26jEP6qqa0zPedw0yVeSnJPkgGn9jTKb/rXkP6epYkmyV5IfToHjlknutIF2K3UtAACwYrankY4nJrlOklcuey76hd39tqq6VZJPT9suTvKozL7ln/fuJHdOclpmIxHP6O7vbKP6vpLZFKfrJnlid19aVZ9McnZmU7G+kNnUryVHJzm9qk5N8tgkT6yq06fjfGZ97br70E1dyxRaAADgaqO6zbzZlKo6Jsl7u/ufF13L1lh989V9yEsPWXQZAOwE1t5/7aYbATusqjqluw9cvn67mV4FAADsmLan6VXbre4+bNE1AADA1ZWRDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKFWLboAxtt3r32z9v5rF10GAAA7KSMdAADAUEIHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMtWrRBbACzj03OfzwRVex7a1du+gKAADYDEY6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKEDAAAYSugAAACGEjoAAIChhA4AAGAooQMAABhK6AAAAIYSOgAAgKGEDgAAYCihAwAAGEroAAAAhhI6AACAoYQOAABgKKFjE6rqsqpaN/ezZiNtD6uql0/Lz62qp2/G8S/exPa9q+pJW1w4AABsJ1YtuoCrgZ909wELPP/eSZ6U5BULrAEAALaakY6tUFXnVNU+0/KBVXXCFux7k6r6dFWdVFXPn1u/R1X9n6o6tarOqKoHTpuOTLLfNMry4o20AwCA7ZKRjk3brarWTctnd/eDr+Lxjkryyu5+Y1U9eW79pUke3N0/ngLNZ6rq+CTPTLL/0mhLVa1aX7vu7qtYFwAADCF0bNq2nl511yQPmZaPTfI/puVK8oKqunuSy5PcIMl117P/htp950qNqp6Q5AlJcuM99tiG5QMAwJYROrbOz3LF1LRdt2L/9Y1KHJpkdZI7dPd/VtU5Gzj2ZrXr7qOTHJ0kB65ebRQEAICF8UzH1jknyR2m5YdspN36fDLJw6flQ+fW75Xku1OQ+J0k+07rL0qy52a0AwCA7ZLQsXWel+Soqvp4ksu2cN+nJnlyVZ2UWYBYclySA6vq5MzCyJlJ0t0/SPLJqvpCVb14Q+0AAGB7VZ4/3vEduHp1n3zIIYsuY9tbu3bRFQAAMKeqTunuA5evN9IBAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDrVp0AayAffdN1q5ddBUAAOykjHQAAABDCR0AAMBQQgcAADCU0AEAAAwldAAAAEMJHQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABDCR0AAMBQ1d2LroHBqup7Sc4dfJp9knx/8Dm4Mn2+8vT5ytPni6HfV54+X3n6fIx9u3v18pVCB9tEVZ3c3Qcuuo6diT5fefp85enzxdDvK0+frzx9vrJMrwIAAIYSOgAAgKGEDraVoxddwE5In688fb7y9Pli6PeVp89Xnj5fQZ7pAAAAhjLSAQAADCV0sEWq6kZV9dGq+nJVfbGqnjqt/9Wq+nBVfXX6fe1F17qj2EifP7eqvlVV66af+yy61h1FVe1aVZ+rqtOmPn/etN59PtBG+t29PlhVXbOqPl9V751eu9cHW0+fu88Hq6pzquqMqX9Pnta511eI6VVskaq6XpLrdfepVbVnklOSPCjJYUku6O4jq+qZSa7d3X+zuEp3HBvp8z9OcnF3v2SR9e2IqqqS7N7dF1fVLkk+keSpSQ6J+3yYjfT7H8a9PlRV/WWSA5P8Snffr6peFPf6UOvp8+fGfT5UVZ2T5MDu/v7cOvf6CjHSwRbp7vO6+9Rp+aIkX05ygyQPTPKGqdkbMvtQzDawkT5nkJ65eHq5y/TTcZ8PtZF+Z6CqumGS+yZ5zdxq9/pAG+hzFsO9vkKEDrZaVa1Jcrskn01y3e4+L5l9SE5ynQWWtsNa1udJ8t+q6vSqep0h4W1rmvqwLsl3k3y4u93nK2AD/Z6410f6pyTPSHL53Dr3+lj/lF/s88R9Plon+VBVnVJVT5jWuddXiNDBVqmqPZK8M8nTuvvHi65nZ7CePn9lkv2SHJDkvCT/uLjqdjzdfVl3H5DkhkkOqqr9F1zSTmED/e5eH6Sq7pfku919yqJr2VlspM/d5+Pdtbtvn+TeSZ5cVXdfdEE7E6GDLTbNtX5nkuO6+13T6vOnZw+WnkH47qLq2xGtr8+7+/zpA9rlSV6d5KBF1rij6u4Lk5yQ2XMF7vMVMt/v7vWh7prkAdNc97cm+d2qelPc6yOtt8/d5+N197en399N8u7M+ti9vkKEDrbI9KDna5N8ubtfOrfp+CSPmZYfk+T/W+nadlQb6vOlvyQnD07yhZWubUdVVaurau9pebck90xyZtznQ22o393r43T333b3Dbt7TZKHJ/lIdz8q7vVhNtTn7vOxqmr36R9jSVXtnuRemfWxe32FrFp0AVzt3DXJo5OcMc27TpJnJTkyydur6nFJvp7kjxZT3g5pQ33+iKo6ILM5quckOXwRxe2grpfkDVV1zcy+nHl7d7+3qj4d9/lIG+r3Y93rK87f6SvvRe7zoa6b5N2z7/GyKsmbu/t/V9VJca+vCP9kLgAAMJTpVQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHADuVquqqOnbu9aqq+l5VvXd6fd2qem9VnVZVX6qq90/r11TVT6pq3dzPnyzqOgCuTvw/HQDsbC5Jsn9V7dbdP0ny+0m+Nbf9iCQf7u6jkqSqbjO37WvdfcCKVQqwgzDSAcDO6ANJ7jstPyLJW+a2XS/JN5dedPfpK1gXwA5J6ABgZ/TWJA+vql2T3CbJZ+e2/a8kr62qj1bVs6vq+nPb9ls2veq3V7JogKsr06sA2Ol09+lVtSazUY73L9v2waq6aZI/THLvJJ+vqv2nzaZXAWwFIx0A7KyOT/KSXHlqVZKkuy/o7jd396OTnJTk7itdHMCOROgAYGf1uiRHdPcZ8yur6ner6pen5T2T7Jfk6wuoD2CHYXoVADul7v5mkqPWs+kOSV5eVT/L7Mu513T3SdN0rP2qat1c29d198uGFwtwNVfdvegaAACAHZjpVQAAwFBCBwAAMJTQAQAADCV0AAAAQwkdAADAUEIHAAAwlNABAAAMJXQAAABD/V8HqUfy3dkHfQAAAABJRU5ErkJggg==\n"
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "x_labels = ['Full data','Zero Imputation','Mean Imputation','Regressor Imputation']\n",
    "colors = ['r', 'g', 'b', 'orange']\n",
    "plt.figure(figsize=(12, 6))\n",
    "ax = plt.subplot(111)\n",
    "for i in np.arange(len(mse)):\n",
    "    ax.barh(i, mse[i],color=colors[i], alpha=0.6, align='center')\n",
    "ax.set_title('Imputation Techniques with Boston Data')\n",
    "ax.set_xlim(left=np.min(mse) * 0.9,\n",
    "            right=np.max(mse) * 1.1)\n",
    "ax.set_yticks(np.arange(len(mse)))\n",
    "ax.set_xlabel('MSE')\n",
    "ax.set_yticklabels(x_labels)\n",
    "plt.show()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "outputs": [
    {
     "data": {
      "text/plain": "0     0\n1     0\n2     0\n3     0\n4     0\n5     0\n6     0\n7     0\n8     0\n9     0\n10    0\n11    0\n12    0\ndtype: int64"
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pd.DataFrame(df_0).isnull().sum()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "name": "pycharm-5a6c15b5",
   "language": "python",
   "display_name": "PyCharm (machine_learning)"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}